spring:
  application:
    name: recommendation-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/MedSystem
    username: postgres
    password: postgres

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka